[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
base1 = "EnYjwQgVud8ZJw3V4zRaVYFc8uT6C7Z1yUsPWeHj6WsJ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://solana-devnet.g.alchemy.com/v2/jhJ-IL_AhWVyx-AVyq76v_yqcTsgcmUO"
wallet = "/opt/sol/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
